### ISSUE TITLE
[core.Config] Replace config file with YAML or JSON?

### ISSUE THREAD

**Issue by ZetaHunter** [Arcbot-Org/Arcbot#36]
Right now the config file is a py file that contains static data, in my opinion config file shouldn't contain such stuff.
Also referencing #35 maybe should make a base config file and then "profiles" for each bot...
Heres how a YAML version of current config would look like: ([Link to YAML online parser](http://yaml-online-parser.appspot.com/?yaml=%0Aconnector%3A+Discord%0Aconnector+options%3A%0A++{username%3A+USERNAME%2C+password%3A+PASSWORD}%0A%0A%23+http%3A%2F%2Fdocs.peewee-orm.com%2Fen%2Flatest%2Fpeewee%2Fplayhouse.html%23connect%0Adatabase+connection%3A+sqlite%3A%2F%2F%2Fbot.db%0A%0Aplugins%3A+%0A++-+Manage%0A++-+Utility%0A++-+Attacks%0A%0Aoptions%3A%0A++ignore+self%3A+True%0A++%23+https%3A%2F%2Fdocs.python.org%2F2%2Flibrary%2Flogging.html%23logging-levels%0A++log+level%3A+0%0A++threaded+workers%3A+3%0A++threaded+pool+queue+size%3A+25%0A++trigger%3A+%22*%22&type=json))
```yaml
connector: Discord
connector options:
  {username: USERNAME, password: PASSWORD}

# http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#connect
database connection: sqlite:///bot.db

plugins: 
  - Manage
  - Utility
  - Attacks

options:
  ignore self: True
  # https://docs.python.org/2/library/logging.html#logging-levels
  log level: 0
  threaded workers: 3
  threaded pool queue size: 25
  trigger: "*"
```

Then back to #35 we'd have (taken from [SO](http://stackoverflow.com/questions/823196/yaml-merge-in-python))
```python
def merge(user, default):
    if isinstance(user,dict) and isinstance(default,dict):
        for k,v in default.iteritems():
            if k not in user:
                user[k] = v
            else:
                user[k] = merge(user[k],v)
    return user
```
Say we have 3 "profiles", we just iterate over them merging Base Yaml with Profile Yaml using that ^ function and spawn processes for each one.
